name: Release to stage
on:
  push:
    branches:
      - stage-cere
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:16-buster'
      build_command: 'npm run build'
      path_to_static_files_to_upload: 'build'
      aws_account_id: ${{ vars.STG_NETWORK_AWS_ACCOUNT_ID }}
      s3_bucket_name: "staking-stg.network-stage.aws.cere.io"